### ISSUE TITLE
Create basic Hyrax testing checklist for prototype

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#135]
In order to perform basic testing with a vanilla Hyrax on top of our migrated data, we need to identify minimal testing criteria for our goal of "read only" assessment. As a point of comparison we can look at the [Nurax repository](https://dev.nurax.samvera.org/?locale=en).

Suggested basic tasks for testing:

As any user:
- [x] Homepage loads
- [ ] Empty search/browse returns indexed OpenEmory work records
- [ ] An individual work record and its indexed metadata can be viewed
- [ ] Filesets attached to a work can be viewed
- [ ] Files attached to a FileSet can be downloaded

As an Admin user
- [ ] Dashboards > Collections shows that the default Admin Set for Hyrax contains migrated works
- [ ] Dashboards > Works shows migrated works
