### ISSUE TITLE
Pilot Migration to Fedora 6

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#26]
## Story
_As a Preservation Curator, I want to assess the complexity of migrating Fedora 3 data to Fedora 6, so that I can effectively plan for future large scale migrations_

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Checklist
- [x] A subset of works is identified including representative samples from the 7 content types, PubMed harvests, and embargoed works
- [x] Migrated content can be viewed for QA purposes in an interface - either in Fedora 6 directly or through a basic default Hyrax 3 interface, or an alternative mechanism for content specialists to assess the content is identified
- [x] The count of works migrated matches the target count identified
- [x] The count of files migrated matches the target count identified
- [ ] The count of filesets migrated matches the target count identified (if applicable)
- [x] Checksums are verified as part of the migration process
- [ ] Metadata should validate against the CurateGenericWork model as a reference and support the existing fields applicable to OpenEmory content
- [ ] If feasible, migrated collection, works, and files should be related using Hyrax and Curate's PDCM model
- [ ] Migrated metadata will be assessed on a tiered scale to identify future cleanup needed (Passed, Needs Remediation, Failed/Missing)

#### Notes
Possible work tasks:

- [x] Document rationale for Fedora 6 testing
- [x] Review metadata mappings for OE to DLP
- [x] Create DLP SIP mapping
- [x] Review/install Fedora 3 > 6 migration tools
- [x] Assess OCFL export needs if applicable
- [x] Identify MVP acceptance criteria for migration assessment
- [x] Review Fedora 6 data model needs
- [x] Review Fedora 6 index/UI capabilities for QA testing
- [x] Identify data model/metadata mappings needed for Fedora 6
- [x] Identify subset of content to migrate
- [x] Investigate Valkyrie options/capability to read Fedora 6 data
- [x] Identify/implement Fedora 6 instance to migrate to
- [x] Identify/implement Hyrax instance to test against
- [x] Identify/implement SOLR instance to test against
- [x] Create QA plan for migration testing
- [x] Perform migration steps
- [x] QA migration
- [ ] Assess and document migration findings
- [x] Document Fedora 6 architecture setup from pilot
- [x] Document any data remediations needed for a full migration

#### Links to Additional Information
Add [links](https://www.emory.edu/) here

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)
