### ISSUE TITLE
Re-enable manual deposit features

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#27]
## Story
_As a Library Deposit Supervisor, I want to provide manual deposit capability in OpenEmory, so that open access material continues to be preserved after Emory FIRST is discontinued_

_As a Faculty/Researcher submitter, I want to deposit my material in OpenEmory, so that I can share my scholarship with the campus and wider academic communities_

_As a Faculty/Researcher submitter, I want to deposit my material in OpenEmory, so that I can fulfill grant/funding requirements related to my publication_

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
Potential tasks:

- [x] Review/test legacy manual deposit functionality
- [x] Review Fedora 3 data models and metadata for additional content types
- [x] Create revised wireframe(s) for new manual deposit interface
- [x] Create revised wireframes/language for assent to deposit and terms of use
- [x] Remediate test environment to be consistent with production
- [x] Update legacy deposit form(s)
- [x] Create functional test plan
- [x] Test deposit capabilities
- [x] Revise public interface to link to deposit forms

#### Links to Additional Information

- [Original wireframes and assent to deposit docs from 2012 development](https://emory.sharepoint.com/:f:/r/sites/EmoryUniversityLibraries/Shared%20Documents/Project%20Management%20Office/EUL%20Projects/01%20Active%20Project/OpenEmory%202023/02%20Planning%20and%20Execution/02%20Technical%20Documentation,%20Drawings%20%26%20Diagrams/Wireframes/2012%20OE%20documents?csf=1&web=1&e=8d1gyV)
- [Metadata inventory of OpenEmory content types](https://docs.google.com/spreadsheets/d/125DXD20_f2qu_irQuMvqFWeWqMIhKxMqiLpM9-pgUvc/edit#gid=0)
- [Fedora 3 Content Type Samples](https://emory.sharepoint.com/:f:/r/sites/EmoryUniversityLibraries/Shared%20Documents/Project%20Management%20Office/EUL%20Projects/02%20Project%20Archive/DLP%20-%20Discovery%20and%20Planning%20Phases/DLP%20Project/Discovery%20Phase%20-%20Current%20State%20Docs/OpenEmory_Sample%20Objects?csf=1&web=1&e=p34NXG)
- [Fedora 3 content models diagrams](https://emory.sharepoint.com/:b:/r/sites/EmoryUniversityLibraries/Shared%20Documents/Project%20Management%20Office/EUL%20Projects/02%20Project%20Archive/DLP%20-%20Discovery%20and%20Planning%20Phases/DLP%20Project/Discovery%20Phase%20-%20Working%20Groups/Repository%20Architecture%20IWG/Deliverables/Current%20State%20Data%20Models/Fedora%203%20Models/OpenEmory/OE-Fedora3-ContentModels.pdf?csf=1&web=1&e=BzBRsf)
- [New Wireframes for 2023 Manual Deposit](https://docs.google.com/drawings/d/1JuHpX2LWuWEkwMSGHtB5HVU8Z2QXmatWKvjN5UMYT5Q/edit)

#### Checklist
- [x] Support for 7 content types and associated metadata fields (Article, Book, Book Chapter, Conference Paper, poster, Report, Presentation)
- [x] Support for required fields depending on the type of content
- [x] Support for any required mime-type enforcement associated with content types

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)
