### ISSUE TITLE
Operational Support

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#28]
## Story
As a Repository Administrator, I want to ensure that OpenEmory functionality is documented, so that we can properly support and troubleshoot in the event of maintenance or incidents

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
Add notes here

#### Links to Additional Information
Add [links](https://www.emory.edu/) here

#### Checklist
- [x] Review and revise OLA as needed for new functionality
- [x] Revise/create support playbook
- [x] Revise regression test plan
- [x] Revise other product documentation as needed for 2023 functional changes

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)
