### ISSUE TITLE
Additional Maintenance - OpenEmory 2023

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/OpenEmory#29]
## Story
_As a Repository Administrator, I want to perform additional maintenance on OpenEmory during our 2023 project, so that we can maximize efficiency of effort for the development team while they are allocated_

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
The items noted here are additional items identified beyond the original scope proposal. They may be accomplished during the project timeline as time permits, but must be carefully prioritized with the project's goals.

#### Links to Additional Information
[MySQL work planning epic](https://app.zenhub.com/workspaces/legacy-systems-5d793aeb3859ca0001801253/issues/gh/emory-libraries/thekeep/38)

#### Checklist

The following items were identified by SCO on 3/9/23:
- [x] Disable/delete the Faculty by Department browse view
- [x] Disable/delete the Works by Department browse view
- [x] Publishing your data link in sidebar
- [x] Privacy policy link in sidebar
- [x] Update static content in the About section (can be performed by SCO staff in Django admin)

The following items were identified by LTDS prior to project kickoff:

- [x] Assess ldap to Shibboleth remediation needs for OpenEmory
- [x] Perform OIT-required MySQL database upgrades for OpenEmory

Other items
- [x] Confirm/document which Google Analytics tags are used in test vs prod

**Comment by eporter23** [comment]
Closing! Thank you @alexBLR !
